name: Lint and test

on:
  push:
    branches: [ "main" ]

jobs:

  lint_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: ./build/scripts/setup.bash
    - name: Lint
      run: ./build/scripts/pylint.bash
    - name: Test
      run: ./build/scripts/test.bash
